"""Checksum manifest for data/interim/10_combined_deduplicated/, mirroring
the data/interim/04_deduplicated/manifest.json pattern
(build_deduplicated_manifest.py), scoped to the round1+round2 combined
layer instead of round1's own 25,191-record snapshot.
"""

from __future__ import annotations

import hashlib
import json
from datetime import datetime, timezone
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[2]
COMBINED_DIR = PROJECT_ROOT / "data" / "interim" / "10_combined_deduplicated"
EXPORT_PATH = PROJECT_ROOT / "data" / "exports" / "2026-08-02_round1_round2_combined" / "titles.jsonl"
EXPORT_MANIFEST_PATH = PROJECT_ROOT / "data" / "exports" / "2026-08-02_round1_round2_combined" / "manifest.json"

PRODUCED_BY = {
    # titles_combined_deduplicated.jsonl is written by
    # flag_exact_duplicates_combined.py, then updated in place by
    # apply_foreign_performer_exclusion_combined.py, then (2026-08-03)
    # updated in place again by apply_full_cleanup_pipeline_combined.py
    # (rules 001->002->004->005->006->008->012->013->014), then (2026-08-04)
    # apply_length_forum_exclusion_combined.py (rule 009) and
    # apply_non_cjk_exclusion_combined.py (rule 011), in that order.
    "data/interim/10_combined_deduplicated/titles_combined_deduplicated.jsonl": (
        "src/preprocessing/apply_non_cjk_exclusion_combined.py"
    ),
    "data/interim/10_combined_deduplicated/duplicate_groups_for_review.csv": (
        "src/preprocessing/export_combined_review_and_analysis_views.py"
    ),
    "data/interim/10_combined_deduplicated/cross_round_duplicate_groups_for_review.csv": (
        "src/preprocessing/export_combined_review_and_analysis_views.py"
    ),
    "data/interim/10_combined_deduplicated/foreign_performer_titles_for_review.csv": (
        "src/preprocessing/export_combined_review_and_analysis_views.py"
    ),
    "data/interim/10_combined_deduplicated/long_or_forum_titles_for_review.csv": (
        "src/preprocessing/export_combined_review_and_analysis_views.py"
    ),
    "data/interim/10_combined_deduplicated/non_cjk_titles_for_review_combined.csv": (
        "src/preprocessing/export_combined_review_and_analysis_views.py"
    ),
    "data/interim/10_combined_deduplicated/titles_for_analysis_combined.csv": (
        "src/preprocessing/export_combined_review_and_analysis_views.py"
    ),
}


def sha256_of(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def line_count(path: Path) -> int:
    with path.open("r", encoding="utf-8", errors="replace") as f:
        return sum(1 for _ in f)


def main() -> None:
    export_sha256 = sha256_of(EXPORT_PATH)
    export_manifest = json.loads(EXPORT_MANIFEST_PATH.read_text(encoding="utf-8"))
    if export_sha256 != export_manifest["sha256"]:
        raise SystemExit("SHA-256 mismatch against the combined export's own manifest.json; refusing to run.")

    entries = []
    for rel_path, rel_script in sorted(PRODUCED_BY.items()):
        path = PROJECT_ROOT / rel_path
        script_path = PROJECT_ROOT / rel_script
        entries.append(
            {
                "output_path": rel_path,
                "output_sha256": sha256_of(path),
                "output_bytes": path.stat().st_size,
                "output_line_count": line_count(path),
                "produced_by_script": rel_script,
                "producing_script_sha256": sha256_of(script_path),
                "input_path": "data/exports/2026-08-02_round1_round2_combined/titles.jsonl",
                "input_sha256": export_sha256,
            }
        )

    report_path = COMBINED_DIR / "report.md"
    additional_files = []
    if report_path.exists():
        additional_files.append(
            {
                "path": "data/interim/10_combined_deduplicated/report.md",
                "sha256": sha256_of(report_path),
                "bytes": report_path.stat().st_size,
                "note": "Hand-authored human-readable summary, not machine-generated by a single script.",
            }
        )

    manifest = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "generated_by": "src/preprocessing/build_combined_deduplicated_manifest.py",
        "additional_files": additional_files,
        "note": (
            "Round1+round2 combined layer (103,743 records, 10 sites). "
            "Cross-round exact-duplicate flagging (same definition as "
            "round1 rule 007: identical original_title strings only), "
            "rule 016 (foreign-performer exclusion, detector function "
            "reused unchanged from round1), (2026-08-03) rules "
            "001->002->004->005->006->008->012->013->014 (cleaned_title, "
            "logic reused unchanged from round1 except two round2-only "
            "supplementary extensions scoped to data_round=='round2' -- "
            "see docs/cleaning_rules.md rule 001/002/012 round2 扩展说明 "
            "sections and docs/research_log.md 2026-08-03 entry), and "
            "(2026-08-04) rules 009/011 (long/forum-post and non-CJK "
            "title exclusion): round1 records' excluded_by_rule_009/011 "
            "fields copied verbatim from round1's own frozen "
            "titles_deduplicated.jsonl (join by record_id, not "
            "recomputed); round2 records computed fresh with the "
            "unchanged round1 detector logic (11 rule-009 hits, 28 "
            "rule-011 hits) -- see apply_length_forum_exclusion_combined.py "
            "/apply_non_cjk_exclusion_combined.py and docs/research_log.md "
            "2026-08-04 entry. "
            "Rules 003/007/009/011/015/016 record-level filtering (003 is "
            "a retracted no-op; 007/009/011/016 are already reflected in "
            "the duplicate/exclusion fields above; 015 -- organizer-prefix "
            "removal -- remains deliberately NOT re-run against round2 in "
            "this layer, still deferred to a later user-directed pass). "
            "data/raw/titles.jsonl and data/interim/04_deduplicated/ "
            "(round1's own frozen outputs) are untouched by this layer -- "
            "verified byte-identical, see docs/research_log.md."
        ),
        "input_snapshot": {
            "path": "data/exports/2026-08-02_round1_round2_combined/titles.jsonl",
            "sha256": export_sha256,
        },
        "outputs": entries,
    }

    out_path = COMBINED_DIR / "manifest.json"
    out_path.write_text(json.dumps(manifest, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"wrote {out_path.relative_to(PROJECT_ROOT)}")
    for e in entries:
        print(f"  {e['output_path']}  sha256={e['output_sha256']}  lines={e['output_line_count']}")


if __name__ == "__main__":
    main()
